### ISSUE TITLE
Undefined Reference error

### ISSUE THREAD

**Issue by antoniomerlin** [uclouvain/openjpeg#853] opened 2016-10-03 06:15 UTC
`Android NDK: WARNING: APP_PLATFORM android-24 is larger than android:minSdkVersi
on 8 in ./AndroidManifest.xml
Android NDK: WARNING:jni/Android.mk:mupdfcore: LOCAL_LDLIBS is always ignored fo
r static libraries
[armeabi-v7a] SharedLibrary  : libmupdf_java.so
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5953: error: undefined
 reference to 'opj_has_thread_support'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5955: error: undefined
 reference to 'opj_thread_pool_destroy'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5958: error: undefined
 reference to 'opj_thread_pool_create'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5962: error: undefined
 reference to 'opj_thread_pool_create'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:6017: error: undefined
 reference to 'opj_thread_pool_create'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:6020: error: undefined
 reference to 'opj_thread_pool_create'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:7614: error: undefined
 reference to 'opj_thread_pool_destroy'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5973: error: undefined
 reference to 'opj_has_thread_support'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5976: error: undefined
 reference to 'opj_get_num_cpus'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/tcd.c:1606: error: undefined
 reference to 'opj_thread_pool_wait_completion'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/dwt.c:647: error: undefined
reference to 'opj_thread_pool_get_thread_count'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/dwt.c:729: error: undefined
reference to 'opj_thread_pool_submit_job'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/dwt.c:731: error: undefined
reference to 'opj_thread_pool_wait_completion'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/dwt.c:793: error: undefined
reference to 'opj_thread_pool_submit_job'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/dwt.c:795: error: undefined
reference to 'opj_thread_pool_wait_completion'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/dwt.c:706: error: undefined
reference to 'opj_thread_pool_wait_completion'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/t1.c:1772: error: undefined
reference to 'opj_thread_pool_submit_job'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/t1.c:1656: error: undefined
reference to 'opj_tls_get'
jni/../../../../thirdparty/openjpeg/src/lib/openjp2/t1.c:1660: error: undefined
reference to 'opj_tls_set'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
make: **\* [obj/local/armeabi-v7a/libmupdf_java.so] Error 1

I am not able to understand what is this error is regarding please help if possible`

**Comment by szukw000** [comment] 2016-10-04 10:31
This error report is obvious. [lib]mupdf has been compiled with an old version of OPENJPEG.
If possible, recompile. 

Please report, what you have done.

winfried


----- Original Nachricht ----
Von:     Gaurav Singh <notifications@github.com>
An:      uclouvain/openjpeg <openjpeg@noreply.github.com>
Datum:   03.10.2016 08:15
Betreff: [uclouvain/openjpeg] Undefined Reference error (#853)

> `Android NDK: WARNING: APP_PLATFORM android-24 is larger than
> android:minSdkVersi
> on 8 in ./AndroidManifest.xml
> Android NDK: WARNING:jni/Android.mk:mupdfcore: LOCAL_LDLIBS is always
> ignored fo
> r static libraries
> [armeabi-v7a] SharedLibrary  : libmupdf_java.so
> jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5953: error:
> undefined
>  reference to 'opj_has_thread_support'
> jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5955: error:
> undefined
>  reference to 'opj_thread_pool_destroy'
> jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5958: error:
> undefined
>  reference to 'opj_thread_pool_create'
> jni/../../../../thirdparty/openjpeg/src/lib/openjp2/j2k.c:5962: error:
> undefined
>  reference to 'opj_thread_pool_create'
(...)

**Comment by antoniomerlin** [comment] 2016-10-04 11:52
i've followed instruction from this url [http://mupdf.com/docs/how-to-build-mupdf-for-android](url),
after make generate i've compiled the android version using ndk-build in that build i've got this error.

**Comment by szukw000** [comment] 2016-10-04 18:37
Sorry, I can not help you. I have trie to compile NDK but found that a lot of
requirements are not met.

winfried


----- Original Nachricht ----
Von:     Gaurav Singh <notifications@github.com>
An:      uclouvain/openjpeg <openjpeg@noreply.github.com>
Datum:   04.10.2016 13:52
Betreff: Re: [uclouvain/openjpeg] Undefined Reference error (#853)

**Comment by antoniomerlin** [comment] 2016-10-05 04:58
can you specify which requirements.

**Comment by szukw000** [comment] 2016-10-05 16:28
@antoniomerlin ,
please forget comment 2.

It is not an issue of LIBOPENJPEG but ANDROID.

The file 'thread.c' was missing. The current LIBOPENJPEG version in ANDROID
is '2.1.0', so I suppose the files are pasted from an older version where no files
'thread.c' and 'thread.h' existed.

But now I am stuck:

ant debug
Buildfile: /home/szukw000/Desktop/MUPDF/mupdf/platform/android/viewer/build.xml

BUILD FAILED
/home/szukw000/Desktop/MUPDF/mupdf/platform/android/viewer/build.xml:80: Cannot find /usr/local/android-studio/tools/ant/build.xml imported from /home/szukw000/Desktop/MUPDF/mupdf/platform/android/viewer/build.xml

Total time: 0 seconds

winfried
[mupdf-report.txt](https://github.com/uclouvain/openjpeg/files/511734/mupdf-report.txt)

**Comment by szukw000** [comment] 2016-10-05 17:12
@antoniomerlin ,
no it is not an issue of ANDROID but MUPDF.

winfried

**Comment by antoniomerlin** [comment] 2016-10-06 11:30
just if possible can you clear me out regarding these method and how to access them.

**Comment by szukw000** [comment] 2016-10-06 11:39
@antoniomerlin ,
the bug has been reported to the MUPDF bugzilla as [Bug 697196] .

I do not understand the line above:
>just if possible can you clear me out regarding these method and how to access them.

What do you mean with 'regarding these method and how to access them'?

And the general problem is: As the bug is not an OPENJPEG bug, this issue list is no longer
the correct list to talk about MUPDF and ANDROID.

winfried

**Comment by rouault** [comment] 2017-07-29 17:05
Closing under the assumption the issue is in mupdf

**Closed by rouault** 2017-07-29 17:05 UTC
