### ISSUE TITLE
MQ Encode :uninitialized memory access when first pass does not output any bytes

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#709] opened 2016-01-29 01:20 UTC
On the first pass of a code block, if there were no bytes output by the mq coder,
then the OpenJPEG mq coder will store a rate of -1 for this first pass.

After a correction factor is added, this is stored as a positive rate of 2. But still, this looks
like a bug to me:  passes with zero rates are given different rates, depending on when they
occur in the code stream.

Also, these lines could cause an access to uninitialized memory:

```
    if((pass->rate>1) && (cblk->data[pass->rate - 1] == 0xFF)){
        pass->rate--;
    }
```

Because the rate is 2, but in fact no data has been output.

Looks like this is currently being reported by valgrind

**Comment by boxerab** [comment] 2016-12-29 19:39
Happy Holidays

**Comment by rouault** [comment] 2017-07-05 23:14
This part of the code has been recently significantly reworked. I believe the above is fixed with that, but difficult to say given there's no reproducer given in the ticket. So closing. Re-open if you believe the issue is still there

**Closed by rouault** 2017-07-05 23:14 UTC
Labels: bug, Priority-Critical
