### ISSUE TITLE
Bypass mode creates artefacts in image

### ISSUE THREAD

**Issue by isenkyr** [uclouvain/openjpeg#934] opened 2017-05-23 07:15 UTC
When i use openJpeg with bypass mode then i get image with artefacts. I attach input image and conversion parameters which i use to conversion. OpenJpeg version 2.1.2

-I  -r 754.256332343635,542.252778413158,389.838391920622,280.264072154672,201.488493100272,144.85485970322,104.139596543597,74.8684275452172,53.8246894469852,38.6958466880406,27.8193625692756,20 -c [256,256],[256,256],[128,128],[128,128],[128,128],[128,128] -p RPCL -n 6 -t 1024,1024 -b 64,64 -SOP -EPH -M 1
![001](https://cloud.githubusercontent.com/assets/19608475/26342424/4fb31d2e-3f98-11e7-9778-2ccd146152dd.png)

**Comment by boxerab** [comment] 2017-05-23 14:15
Congratulations!  Your command line arguments produce images that cannot be decoded.
Looks like you've discovered a bug in the library.

**Comment by boxerab** [comment] 2017-05-23 14:29
Here is a minimal command line to re-create the bug:

`-r 53,38,27,20  -M 1`

**Comment by rouault** [comment] 2017-05-23 15:21
Isn't it a duplicate of #674 ?

**Comment by boxerab** [comment] 2017-05-23 15:25
Yes, I suppose you're right.  But, in 674, images could be decoded, while here, the packet headers seem to be corrupt.

**Comment by boxerab** [comment] 2017-05-26 18:58
@isenkyr Bravo! Your choice of command-line parameters uncovers a host of problems with the library's lossless encode mode.

Can you tell us a bit about your use case ? Why do you need so many quality layers, and why do you prefer bypass mode ? Just curious.

**Comment by boxerab** [comment] 2017-05-27 03:49
@isenkyr if you would like to encode in BYPASS mode without artifacts, you can check out Grok codec
 https://github.com/GrokImageCompression/grok  
Your command line parameters will work unchanged, and I have verified that BYPASS works correctly in your case.

**Comment by rouault** [comment] 2017-06-13 10:48
Fixed per https://github.com/uclouvain/openjpeg/pull/949

**Closed by rouault** 2017-06-13 10:48 UTC
