### ISSUE TITLE
opj_compress.exe, command line parser, infinite loop

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#469] opened 2015-01-12 14:59 UTC
Originally reported on Google Code with ID 469

```
If the argument for -F option is forgotten, 
the parser falls into infinite loop
with the message "F: option requires an argument"

```

Reported by `alexey.k@dxdy.ru` on 2015-01-12 14:59:08

**Comment by rouault** [comment] 2017-08-18 09:17
Duplicate of #736 now fixed

**Closed by rouault** 2017-08-18 09:17 UTC
Labels: bug, Priority-Medium
