### ISSUE TITLE
UB in ht_dec.c opj_t1_ht_decode_cblk - memcpy invoked on NULL pointer

### ISSUE THREAD

**Issue by pauldreik** [uclouvain/openjpeg#1444] opened 2022-08-25 11:31 UTC
Using ubsan and afl, I found that memcpy can be invoked on a null pointer, which is undefined behaviour.

See #1442 for code to reproduce it.

**Comment by rouault** [comment] 2023-12-08 15:25
likely duplicate of https://github.com/uclouvain/openjpeg/pull/1492

**Closed by rouault** 2023-12-08 15:25 UTC
