### ISSUE TITLE
Custom data type in opj_image_comp

### ISSUE THREAD

**Issue by novalain** [uclouvain/openjpeg#913] opened 2017-04-27 22:16 UTC
It seems like the data decoded into an `opj_image_comp` has to be of type `OPJ_INT32`. It would be great if the type here could be specified to say `OPJ_BYTE`. Sometimes the precision of the image to decode is known those cases it's a waste of bytes to always have to decode as `OPJ_INT32`.

**Comment by rouault** [comment] 2017-07-29 17:07
Duplicate of #836

**Closed by rouault** 2017-07-29 17:07 UTC
